sudo: required
services:
  - docker

before_install:
  - docker build -t brianuniacke/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true  brianuniacke/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-680602579453"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
